### ISSUE TITLE
remark-heading-id extension not used when run before remark processor

### ISSUE THREAD

**Issue by rachmari** [electron/hubdown#39]
@wooorm Zeke forwarded me to you as the maintainer of remark and the Unified.js ecosystem. The [docs](https://github.com/unifiedjs/handbook#writing-a-plugin-to-modify-headings) provided for Unified.js are excellent! 🙌 I'm testing out adding an extension and also looking at writing a new extension, and I'm running into some issues. Can you confirm if this is a bug in the extension or hubdown?

I'm testing out the [`remark-heading-id`](https://github.com/imcuttle/remark-heading-id) extension and it seems that the placement of the extension in the `runBefore` list determines whether it works or not. 

When the `remark-heading-id` extension is listed first [in this pull request](https://github.com/github/docs/pull/2794/files#diff-891b6041e0c43765ae64cf8edc4f30e5c23e2822d1d938b6f4b4185470f2412cR62-R63), the extension works:

<img width="799" alt="Screen Shot 2021-01-11 at 9 17 52 PM" src="https://user-images.githubusercontent.com/9831992/104273536-cb042f80-5453-11eb-9570-3a4b40cbf426.png">

When it's not listed first, the custom id is rendered as part of the heading:

<img width="798" alt="Screen Shot 2021-01-11 at 9 18 12 PM" src="https://user-images.githubusercontent.com/9831992/104273486-bcb61380-5453-11eb-8124-9a30076d7aaa.png">

**Comment by wooorm** [comment]
Hi Rachael! Thank you :)

`remark-heading-id` is a community project, so it could definitely be a bug there. From a glance at the code though, it looks fine.

`runbefore` is a hubdown option, so that’s more a thing for @zeke. However, from a glance at the code it seems that `runbefore` should be an array of things: where each thing is either a single plugin, or an array where the first thing is a plugin, and the second the options. That leads me to believe that the following might work:

```js
      runBefore: [
        [remarkCodeExtra, { transform: codeHeader }],
        remarkHeadingId
      ]
```

**Comment by rachmari** [comment]
@wooorm thank you so much! This is super helpful. I'm very new to the Unified.js ecosystem. 🙇‍♀️ I'll give that a try!
